[#1]
    This is the LITE version of the AWARD WINNING Installer
    and UnInstaller for Windows 9x/NT/2000/XP.
  
    Chief's Installer Pro v1.x won the GOLD AWARD
    of the PC PLUS Magazine (April 1995, U.K.).

    Version 5.x for Win32 is even MUCH BETTER than before!

[#2]
    FREEWARE version!

    Greater functionality than many commercial
    installers (which cost A LOT OF MONEY!)

    TREMENDOUS VALUE.

    Royalty Free!!!

[#3]
    Chief's Installer Lite for Win32

    A Great Win32 Installer

    Based on an AWARD WINNING product!

    For more details, email: African_Chief@bigfoot.com
